openapi: 3.0.2

info:
  title: '[Grupo 3] Especificación API REST Recambios'
  version: '1.0.0'

paths:
  /recambios:
    get:
      summary: Obtiene todos los recambios registrados del inventario
      description: |
        Los códigos de estado que puede devolver este endpoint son:
        | Status Code | Descripción          | Motivo                                                    |
        |-------------|----------------------|-----------------------------------------------------------|
        | **200**     | `OK`                 | Hay recambios registrados                                 |
        | **304**     | `NOT MODIFIED`       | Los recambios de la lista no han sido modificados         |
        | **400**     | `BAD REQUEST`        | Se ha introducido algún valor erróneo en la consulta      |
        | **404**     | `NOT FOUND`          | No existen recambios registrados                          |
      operationId: recambios_cget
      parameters:
        - $ref: "#/components/parameters/pageParam"
        - $ref: "#/components/parameters/limitParam"
        - $ref: "#/components/parameters/orderParam"
        - $ref: "#/components/parameters/orderingParam"
        - $ref: "#/components/parameters/nombreFilterParam"
        # TODO: Añadir ETag para caché
      responses:
        '200':
          description: >
            Lista de los recambios registrados
            y links a las páginas `first`, `last`,
            `prev` (si no es la primera) y `next` (si no es la última)
          #headers:
          #  ETag:
          #    $ref:
          content:
            application/json:
              schema:
                type: object
                properties:
                  recambios:
                    description: Lista de recambios
                    type: array
                    items:
                      $ref: "#/components/schemas/Recambio"
                  links:
                    description: Enlaces de paginación
                    type: object
                    properties:
                      first:
                        $ref: "#/components/schemas/Link"
                      last:
                        $ref: "#/components/schemas/Link"
                      prev:
                        $ref: "#/components/schemas/Link"
                      next:
                        $ref: "#/components/schemas/Link"
        '400':
          description: '`BAD REQUEST`: Se ha introducido algún valor erróneo en la consulta.
                        Por ejemplo, se ha introducido un número de página menor que `1`
                        o el límite introducido es menor que `0`.'
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/HTTP_Problem"
              examples:
                response-http-400-recambios-get:
                  value:
                    type: https://httpstatuses.com/400
                    title: BAD REQUEST
                    status: 400
                    detail: Se ha introducido algún valor erróneo en la consulta.
                    instance: about:blank
        '304':
          $ref: '#/components/responses/Response_304'
        '404':
          $ref: '#/components/responses/Response_404'

components:
  schemas:
    Recambio:
      description: 'Información de un recambio'
      title: '⚙ Recambio'
      type: object
      required:
        - nombre
        - proveedor
        - modelo
        - cantidad
        - precio
      properties:
        id:
          type: integer
          format: int32
          description: Id de un recambio. Existe un único id para cada nombre + proveedor + modelo
          readOnly: true
        nombre:
          type: string
          description: Nombre del recambio
        descripcion:
          type: string
          description: Descripción del recambio
        proveedor:
          type: string
          description: Proveedor del recambio
        modelo:
          type: string
          description: Modelo del recambio
        equivalencias:
          type: array
          items:
              $ref: '#/components/schemas/Recambio'
          description: Referencia a otros recambios equivalentes
        cantidad:
          type: integer
          format: int32
          minimum: 0
          description: Cantidad de recambios
        vehiculos_compatibles:
          type: array
          items:
            type: string
          description: Lista de vehículos compatibles con el recambio
        peso:
          type: number
          format: float
          minimum: 0
          description: Peso del recambio en kilogramos
        dimensiones:
          type: object
          properties:
            alto:
              type: number
              format: float
              minimum: 0
              description: Alto en centímetros
            ancho:
              type: number
              format: float
              minimum: 0
              description: Ancho en centímetros
            largo:
              type: number
              format: float
              minimum: 0
              description: Largo en centímetros
          description: Dimensiones del recambio
        precio:
          type: integer
          format: int32
          minimum: 0
          description: Precio unitario de los recambios en euros
    HTTP_Problem:
      type: object
      externalDocs:
        url: https://tools.ietf.org/html/rfc7807
      description: Problem Details for HTTP APIs
      properties:
        type:
          type: string
          format: uri
          description: A URI reference [RFC3986] that identifies the problem type
        title:
          type: string
          description: short human-readable summary of the problem type
        status:
          type: number
          description: HTTP status code
        detail:
          type: string
          description: human-readable explanation specific to this occurrence of the problem
        instance:
          type: string
          format: uri
          description: "A URI reference that identifies the specific
                occurrence of the problem. It may or may not yield further
                information if dereferenced"
    Link:
      description: Enlace de relación
      title: '🔗 Link'
      type: object
      properties:
        href:
          description: URL del enlace
          type: string
          format: url
          x-faker: internet.url
        rel:
          description: "Relación del documento enlazado con el actual. Contiene una lista de tipos
                        de enlaces separados por espacio."
          type: string
          x-faker: lorem.words
  parameters:
    pageParam:
      name: page
      in: query
      description: Número de página
      required: false
      allowEmptyValue: false
      schema:
        type: integer
        minimum: 1
        default: 1
    limitParam:
      name: limit
      in: query
      description: >
        Número de recambios devueltos por cada página.
        Si es `0`, devuelve todos los recambios en una única página
      required: false
      allowEmptyValue: false
      schema:
        type: integer
        minimum: 0
        default: 10
    orderParam:
      name: order
      in: query
      description: 'Ordenación por: `id` | `nombre` | `proveedor` | `cantidad` | `precio`'
      required: false
      allowEmptyValue: false
      schema:
        type: string
        enum:
          - id
          - nombre
          - proveedor
          - cantidad
          - precio
        default: id
    orderingParam:
      name: ordering
      in: query
      description: 'Tipo de ordenación: `ASC` | `DESC`'
      required: false
      allowEmptyValue: false
      schema:
        type: string
        enum:
          - ASC
          - DESC
        default: ASC
    nombreFilterParam:
      name: nombreFilter
      in: query
      description: Filtro por nombre. Puede ser un substring del nombre
      required: false
      allowEmptyValue: false
      schema:
        type: string
  responses:
    Response_404:
      description: '`NOT FOUND`: recurso no disponible'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-404:
              $ref: '#/components/examples/response-http-404'
    Response_304:
      description: '`NOT MODIFIED`: El recurso solicitado no ha sido modificado'
      #headers:
      #  ETag:
      #    $ref:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-304:
              $ref: '#/components/examples/response-http-304'
  examples:
    response-http-404:
      value:
        type: https://httpstatuses.com/404
        title: NOT FOUND
        status: 404
        detail: El recurso solicitado no está disponible.
        instance: about:blank
    response-http-304:
      value:
        type: https://httpstatuses.com/304
        title: NOT MODIFIED
        status: 304
        detail: El recurso solicitado no ha sido modificado.
        instance: about:blank